name: wfh_companion
description: Work from home companion 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  noise_meter: ^1.0.1
  flutter_duration_picker: ^1.0.0
  flutter_ringtone_player: ^2.0.0
  permission_handler: ^5.0.0+hotfix.3
  fluttertoast: ^4.0.0
  tmdb_api: ^1.0.1-stable

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/configs/
    - assets/images/

  uses-material-design: true
